name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up the Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      # Install Node.js dependencies
      - name: Install dependencies
        run: npm install

      # Run the custom index.js script
      - name: Run index.js
        run: node index.js

      # Build the site using Jekyll
      - name: Build site with Jekyll
        uses: actions/jekyll-build-pages@v1

      # Upload the generated site for deployment
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./_site

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
